// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjFsDfg-ReInUDNU-og5sIpBEokRhBuPg',
    appId: '1:717332727748:android:a4a972eed25b698a2d4691',
    messagingSenderId: '717332727748',
    projectId: 'cookbook-2a708',
    storageBucket: 'cookbook-2a708.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkwKUhq2lJIk1CmglqeIzFqawJI1-DX-0',
    appId: '1:717332727748:web:9aece9bf8ec29a9f2d4691',
    messagingSenderId: '717332727748',
    projectId: 'cookbook-2a708',
    authDomain: 'cookbook-2a708.firebaseapp.com',
    storageBucket: 'cookbook-2a708.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoUe13ax6JWQ0SwEu4dweexs5zoaJlcb8',
    appId: '1:717332727748:ios:b97ab4f2e5d0f38f2d4691',
    messagingSenderId: '717332727748',
    projectId: 'cookbook-2a708',
    storageBucket: 'cookbook-2a708.appspot.com',
    iosBundleId: 'com.clockworks.cookbook',
  );

}